# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 15
# Issues with these labels will never be considered stale
exemptLabels:
  - "Status: Accepted"
  - "Status: Under Consideration"
  - "Status: Review Needed"
# Label to use when marking an issue as stale
staleLabel: "Status: Stale"
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: |
  This issue has been automatically marked as stale because it has not had recent activity.

  If this is a **bug report** or a **post error** and you didn't hear from us, please reply with any additional information you have about it in order to keep the issue open.

  If this is a **new post** request, please consider whether it can be accomplished in another way. If it cannot, please elaborate on why it is important to you that we talk about it or why people would like to read about it.

  This issue will automatically be closed in 15 days if no further activity occurs. Thank you for all your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: |
  No aditional comments were found in this issue, so we are closing it due to inactivity.

  Thank you for all your contributions.
